# Generated by Django 3.1 on 2020-08-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200821_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('refine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.refine')),
            ],
        ),
        migrations.RemoveField(
            model_name='refine',
            name='product',
        ),
        migrations.AddField(
            model_name='refine',
            name='product',
            field=models.ManyToManyField(through='product.Filter', to='product.Product'),
        ),
    ]
