# Generated by Django 3.0.3 on 2020-08-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=64)),
                ('numbering', models.IntegerField()),
                ('url', models.CharField(max_length=2048)),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Target')),
            ],
        ),
    ]
