# Generated by Django 3.0.3 on 2020-08-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainimage',
            old_name='url',
            new_name='info',
        ),
    ]
