# Generated by Django 3.0.3 on 2020-08-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('birth', models.CharField(max_length=128, null=True)),
                ('newsletter', models.BooleanField()),
                ('top_contributor', models.BooleanField()),
            ],
        ),
    ]
