# Generated by Django 3.0.3 on 2020-08-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='newsletter',
            new_name='is_newsletter_subscribed',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='top_contributor',
            new_name='is_top_contributor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
