# Generated by Django 3.0.3 on 2020-08-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200824_0037'),
        ('user', '0006_auto_20200824_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(related_name='wish', through='user.Wishlist', to='product.Product'),
        ),
    ]
