# Generated by Django 3.0.3 on 2020-08-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200824_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbag',
            name='size',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
