# Generated by Django 3.0.3 on 2020-08-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200825_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbag',
            name='size',
        ),
    ]
