# Generated by Django 3.0.3 on 2020-08-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_shoppingbag_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbag',
            name='size',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
